import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { Providers } from "./Redux/Provider";
import CustomCursor from "./components/CustomCursor/CustomCursor";
import Header from "./components/Header/Header";
import Skills from "./components/Skills/Skills";
import Sidebar from "./components/Sidebar/Sidebar";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <head>
        <link
          rel="stylesheet"
          href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.4.2/css/all.min.css"
        />
      </head>
      <body className={inter.className}>
        <Providers>
          <div className="bg-white h-screen w-screen flex items-center px-2 pb-0">
            <div className="hidden lg:block h-full w-[20%]">
              <Sidebar />
            </div>
            <div className="w-full lg:w-[80%] h-full overflow-scroll">
              <Header />
              {children}
            </div>
          </div>
          <CustomCursor />
        </Providers>
      </body>
    </html>
  );
}
